# Generated by Django 2.0.5 on 2018-05-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180523_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
