# Generated by Django 2.0.5 on 2018-05-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gmailaddress', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=50)),
                ('dateofbirth', models.DateTimeField(verbose_name='data published')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
