# Generated by Django 2.0.5 on 2018-05-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
